FROM oven/bun:1 as base
WORKDIR /usr/src/app

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ENV NODE_ENV=production
RUN --mount=type=secret,required=true,id=env export $(cat /run/secrets/env | xargs) \
    && bun run build

FROM caddy:alpine AS release
COPY --from=prerelease /usr/src/app/dist /usr/share/caddy
